In [2]:
import numpy as np

In [38]:
# Возьмём квартиру из описания выше и представим её неким вектором apartment:


apartment = np.array([59.50, 31.40, 19, 2, 60550, 2], dtype=int)
apartment

array([   59,    31,    19,     2, 60550,     2])

In [39]:
apartment[1]

31

In [40]:
apartment[0]

59

In [41]:
# Упростим себе задачу оценки новой квартиры — сгенерируем новый признак — отношение жилой площади к общей. А от старых признаков смело избавимся, сократив векторное пространство нашего объекта.

# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]
share_living_space

0.5254237288135594

In [42]:
apartment

array([   59,    31,    19,     2, 60550,     2])

In [43]:
# Избавимся от старых признаков, посредством функции delete(), которую предоставляет библиотека numpy. Передадим в значение функции индексы признаков, которые необходимо удалить из нашего массива apartment:

apartment_new = np.delete(apartment, [0, 1])
apartment_new

array([   19,     2, 60550,     2])

In [37]:
# И в завершение добавим в конец нашего массива новый признак share_living_space, который сочетает в себе смысл двух старых признаков:

apartment_new2 = np.append(apartment_new, share_living_space)
apartment_new2

array([1.90000000e+01, 2.00000000e+00, 6.05500000e+04, 2.00000000e+00,
       5.25423729e-01])

In [20]:
apartment

array([1.90000000e+01, 2.00000000e+00, 6.05500000e+04, 2.00000000e+00,
       5.25423729e-01])

In [ ]:
# В NumPy вектор и массив - одно и то же. 
# Исключение - понятие вектор-столбец и вектор-строка - фактически двумерные массивы, 
# где один из атрибутов shape равен 1.

In [9]:
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

shape: (5,)


In [10]:
print("ndim:", apartment.ndim) # число осей (измерений) массива - n.dim: 1

ndim: 1


In [49]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
t.mean()
t[5]
t.min()
t[2]
t.max()

31

In [51]:
x = np.array([5, 2])
y = np.array([-5, -11])

x + y

array([ 0, -9])

In [54]:
alex_income = np.array([120000, 150000, 90000])
alex_wife_income = np.array([130000, 130000, 130000])
euro_rur_currency = 72
alex_mother_in_law_income = np.array([2000, 3000, 2500]) * euro_rur_currency

print(alex_income)
print(alex_wife_income)
print(alex_mother_in_law_income)

family_income = alex_income + alex_wife_income + alex_mother_in_law_income

print(family_income)

[120000 150000  90000]
[130000 130000 130000]
[144000 216000 180000]
[394000 496000 400000]


In [55]:
x = np.array([4, 5])
y = np.array([2, 1])
z = np.array([1, 0])

2*x + -3*y + 5*z 

array([7, 7])

In [81]:
# Длина вектора

%time

x = np.array([4, 6, 1])

%timeit z = np.sqrt( (x*x).sum() )
z

Wall time: 0 ns
3.7 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


7.280109889280518

In [66]:
x = np.array([4, -1])
y = np.array([1, 4])

np.dot(x,y)

0

In [82]:
"""
На самом деле в Numpy для этого имеется специальная функция, поскольку это достаточно распространённая операция.

Функция является частью модуля linalg библиотеки Numpy, в состав которого входят также множество других распространённых функций линейной алгебры.
Попробуем ещё раз с помощью linalg:

"""

%time

x = np.array([4, 6, 1])

%timeit z = np.linalg.norm(x)

z

Wall time: 0 ns
5.65 µs ± 390 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


7.280109889280518

In [74]:
# Вывод магических команд в Юпитере

%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 