2.3. Случай «Идеальная пара»

Решите систему линейных уравнений

4x + 7y = 20
5x + 10y = 30

Решение

(Использую Метод Гаусса (последовательного исключения неизвестных. Вариант решения взят отсюда: http://mathprofi.ru/metod_gaussa_dlya_chainikov.html)

4 7 | 20
5 10 | 30

Наша цель – с помощью элементарных преобразований привести матрицу к ступенчатому виду.


Смотрим на левую верхнюю «ступеньку». Там у нас должна быть единица. Проблема состоит в том, что в первом столбце единиц нет вообще, поэтому перестановкой строк ничего не решить. В таких случаях единицу нужно организовать с помощью элементарного преобразования. Обычно это можно сделать несколькими способами.


Я поступил так:

К первой строке прибавляем вторую строку, умноженную на –1. То есть, мысленно умножили вторую строку на –1 и выполнили сложение первой и второй строки, при этом вторая строка у нас не изменилась.

-1 -3 | -10
5 10 | 30

Попутно сократим вторую строчку (кратно 5)

-1 -3 | -10
1 2 | 6

Теперь слева вверху «минус один», что нас вполне устроит. Кто хочет получить +1, может выполнить дополнительное телодвижение: умножить первую строку на –1 (сменить у неё знак).

Теперь первая строка у нас останется неизменной до конца решения. Уже легче.

Единица в левом верхнем углу организована. Теперь нужно получить нули во второй строчке вместо 0:

-1 -3 | -10
1 2 | 6

Для этого просто прибавляем первую строчку ко второй на место второй, а первую оставляем как есть:

-1 -3 | -10
0 -1 | -4

Поменяем знак во второй строчке:

-1 -3 | -10
0 1 | 4

y = 4

-1x - 3y = -10
y = 4

-x - 12 = -10

x + 12 = 10

x = -2

Проверяем:

4x + 7y = 20
4 * (-2) + 7 * (4) = 20
-8 + 28 = 20

5 * (-2) + 10 * (4) = 30
-10 + 40 = 30

Как найти ранг матрицы?

http://mathprofi.ru/rang_matricy.html

Как вычислить определитель?

http://mathprofi.ru/kak_vychislit_opredelitel.html

Свойства определителя. Понижение порядка определителя

http://mathprofi.ru/svoistva_opredelitelya_ponizhenie_poryadka_opredelitelya.html

Действия с матрицами

http://mathprofi.ru/deistviya_s_matricami.html

Однородные системы линейных алгебраических уравнений

http://www.mathprofi.ru/odnorodnye_sistemy_lineinyh_uravnenij.html

Решение систем линейных уравнений. Несовместные системы.
Системы с общим решением. Частные решения

http://www.mathprofi.ru/slu_nesovmestnye_sistemy_i_sistemy_s_obshim_resheniem.html

Как решить систему линейных уравнений?

http://mathprofi.ru/kak_reshit_sistemu_uravnenii.html

Аналитикам: большая шпаргалка по Pandas

http://smysl.io/blog/pandas/

Серия уроков по обработке данных

https://pythonworld.ru/obrabotka-dannyx

Решение квадратного уравнения
    
http://mathprofi.ru/goryachie_formuly.pdf


Комплексные числа для чайников

http://mathprofi.ru/kompleksnye_chisla_dlya_chainikov.html

In [3]:
import numpy as np

In [13]:
# Вычислите вектор ошибок для приближённого решения системы w

A = np.array([[1,-5],[2,1],[1,1]])
A

array([[ 1, -5],
       [ 2,  1],
       [ 1,  1]])

In [15]:
w = np.array([1,1])
w

array([1, 1])

In [16]:
np.dot(A,w)

array([-4,  3,  2])

In [ ]:
A.T@A

In [14]:
B = np.array([1,2,2])

In [17]:
B - np.dot(A,w)

array([ 5, -1,  0])

In [ ]:
A.T@B

In [18]:
# Найдите OLS оценку для коэффициентов w1, w2 СЛАУ

A = np.array([[1,2],[-3,1],[1,2],[1,-1]])

B = np.array([1,4,5,0])

In [24]:
A.T@A

array([[12,  0],
       [ 0, 10]])

In [22]:
a = A.T@A

In [23]:
np.diag(a)

array([12, 10])

In [25]:
np.diag(np.diag(a))

array([[12,  0],
       [ 0, 10]])

In [28]:
A.T@B

array([-6, 16])

In [42]:
b = A.T@B


A_1 = np.linalg.inv(A.T@A) # тоже самое, что A_2

A_2 = np.linalg.matrix_power(A.T@A, -1) # тоже самое, что A_1


In [38]:
# A_1 = np.array([[10,0],[0,12]])
# A_1

In [43]:
w = A_2 * b
w

array([[-0.5,  0. ],
       [-0. ,  1.6]])

In [44]:
"""
Используя данные, полученные нами в модуле ранее (см. таблицу и результат применения OLS к ней)
сделайте прогноз типичной стоимости (в тыс. долларов) дома в городке
с уровнем преступности CRIM = 0.2
и средним количеством комнат в доме RM = 6.

"""

CRIM = 0.2
RM = 6
N = 506
k = 2

w0 = -29.3
w1 = -0.26
w2 = 8.4

y = w0 + w1 * CRIM + w2 * RM
y

21.048000000000005

In [49]:
x = np.array([11,8])

x_mean = (11 + 8) / 2

print(x_mean)

x_centr = x - np.array([x_mean,x_mean])

print(x_centr)

x_norm = np.sqrt(1.5**2 + 1.5**2)

print(x_norm)

x_st = 1/x_norm * x_centr

print(x_st)

9.5
[ 1.5 -1.5]
2.1213203435596424
[ 0.70710678 -0.70710678]
