In [2]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[10,  8, 10],
       [ 5,  7, 11],
       [10,  7, 10]])

In [4]:
B

array([[ 1,  1,  1],
       [ 3,  2,  0],
       [-1,  0,  3]])

In [5]:
# Поэлементное умножение
A*B

array([[ 10,   8,  10],
       [ 15,  14,   0],
       [-10,   0,  30]])

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[24 26 40]
 [15 19 38]
 [21 24 40]]


In [7]:
# Матричное умножение
np.dot(A,B)

array([[24, 26, 40],
       [15, 19, 38],
       [21, 24, 40]])

In [8]:
# Матричное умножение
A@B

array([[24, 26, 40],
       [15, 19, 38],
       [21, 24, 40]])

In [9]:
# Порядок умножения AB != BA
B@A

array([[25, 22, 31],
       [40, 38, 52],
       [20, 13, 20]])

In [14]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 5  6 10 10  7]
 [ 6  5  7 10  6]
 [10 10  9  6  9]]
B:
 [[ 3  1]
 [-2 -2]
 [ 0  1]
 [ 0  3]
 [-2  1]]


In [15]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[-11,  40],
       [ -4,  39],
       [ -8,  26]])

In [16]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [23]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (2, 3)
shape of B: (5, 2)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

In [18]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 3 -1  0  2]
 [-3  2  1 -2]
 [ 3  3 -2 -1]
 [ 2 -1 -1  1]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 3 -2  0 -2]
 [-3  4  0  2]
 [ 3  6  0  1]
 [ 2 -2  0 -1]]
DA:
 [[ 3 -1  0  2]
 [-6  4  2 -4]
 [ 0  0  0  0]
 [-2  1  1 -1]]


In [22]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [20]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [24]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [25]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [26]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [27]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [28]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [ ]:
# Задачи

In [34]:
# Даны матрица A и вектор x.

A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

# Найдите произведение матрицы  и вектора x в том порядке, в котором их можно умножить.

A@x

array([26, 30])

In [39]:
# Даны две матрицы:

A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

# Найдите произведение матриц A и B в том порядке, в котором их можно умножить.

C = B@A

# В ответ запишите элемент из 1 строки и 4 столбца

C[0,3]

14

In [41]:
# Дана система векторов:

x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

# Найдите матрицу Грама системы векторов x, y, z

A=np.array([x,y,z])

A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [70]:
"""
В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

"""

import pandas as pd


Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [47]:
print(Count_DF)
print(Price_DF)

       Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28
       Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5         

In [63]:
# преобразовать из Pandas DataFrame в Матрицу

C = Count_DF.values

P = Price_DF.values

print(C)

print(P)


[[10  5 12 15 10]
 [ 2 21  3 25  6]
 [12 12  0 30  4]
 [ 4  8 18 14  5]
 [ 6 25 27 25 18]
 [10  3  2 17 12]
 [22  1  4 25 20]
 [ 7  0 31 31 28]]
[[2.  1.5 1.  0.8 1. ]
 [1.8 2.5 1.  1.  1. ]
 [2.  2.  0.  0.5 2. ]
 [1.8 1.2 2.8 0.8 2. ]
 [2.5 3.5 2.  1.  1.5]
 [5.  5.  3.  2.  2.5]
 [1.1 1.  1.5 0.5 1.7]
 [4.5 4.  2.5 1.  2. ]]


In [52]:
# Найдите вектор выручки Бориса

Income = Count_DF.values * Price_DF.values

print(Income[1])

[ 3.6 52.5  3.  25.   6. ]


In [64]:
# Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

# Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]

com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

salon_inc = (P*C)@(com) #P*C - поэлементно умножаем две матрицы (количество выполненных работ на стоимость работы), а потом делаем поматричное умножение на комиссию салона

print(salon_inc)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [65]:
# Найдите вектор прибыли стилистов.

styl_inc = (P*C)@(np.ones(5)-com)

print(styl_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


In [67]:
A=np.array([[1,2],[2,5]])
np.linalg.inv(A)

array([[ 5., -2.],
       [-2.,  1.]])

In [68]:
A=np.array([[2,0,0],[0,4,0],[0,0,5]])
np.linalg.inv(A)

array([[0.5 , 0.  , 0.  ],
       [0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.2 ]])

In [72]:
A=np.array([[2,0,0],[0,1,0],[0,0,4]])
print(np.linalg.det(A))
print(1/np.linalg.det(A))



7.999999999999998
0.12500000000000003


In [74]:
A=np.array([[1,2], [1,1]])

B=np.array([[5,-2],[-1,4]])

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print(det_A)
print(det_B)
print(det_B + det_A)

-1.0
17.999999999999996
16.999999999999996


In [3]:
A=np.array([[0,0,1,0], [0,0,0,1], [1,0,0,0], [0,1,0,0]])
A

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [4]:
np.linalg.matrix_rank(A)

4

In [5]:
B=np.array([[0,1,3], [2,0,4], [-2,-1,-4]])
B

array([[ 0,  1,  3],
       [ 2,  0,  4],
       [-2, -1, -4]])

In [6]:
np.linalg.det(B)

-6.0