In [78]:
import numpy as np

In [2]:
# как создать матрицу?

In [3]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [4]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# размер матрицы
np.shape(A)

(4, 3)

In [6]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [7]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [8]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [9]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


In [ ]:
# создание специальных матриц

In [10]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [15]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [16]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [17]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

In [18]:
A+B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [19]:
B+A

array([[2, 0],
       [0, 6],
       [8, 0]])

In [20]:
A-B

array([[ 0,  2],
       [ 4,  0],
       [ 0, 10]])

In [21]:
2*A

array([[ 2,  2],
       [ 4,  6],
       [ 8, 10]])

In [22]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

In [23]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

array([1, 2, 3])

In [24]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [25]:
x_col.T

array([[1, 2, 3]])

In [26]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


In [27]:
# Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы NumPy

In [28]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [33]:
Inc = np.array( [ [Husband_Income] , [Wife_Income] , [Mother_In_Law_Income] ] )
Inc

array([[[100, 220, 140]],

       [[150, 200, 130]],

       [[ 90,  80, 100]]])

In [31]:
Inc.T

array([[[100, 150,  90]],

       [[220, 200,  80]],

       [[140, 130, 100]]])

In [34]:
Cons = np.array( [ [Husband_Сonsumption] , [Wife_Сonsumption] , [Mother_In_Law_Сonsumption] ] )
Cons

array([[[ 50,  50,  60]],

       [[100,  80, 140]],

       [[100,  20, 140]]])

In [35]:
Cons.T

array([[[ 50, 100, 100]],

       [[ 50,  80,  20]],

       [[ 60, 140, 140]]])

In [42]:
Inc_After_Tax = (Inc - Inc*0.13).T
Inc_After_Tax

array([[[ 87. , 130.5,  78.3]],

       [[191.4, 174. ,  69.6]],

       [[121.8, 113.1,  87. ]]])

In [39]:
(Inc - Cons)

array([[[ 50, 170,  80]],

       [[ 50, 120, -10]],

       [[-10,  60, -40]]])

In [43]:
Inc_After_Tax - Cons.T

array([[[ 37. ,  30.5, -21.7]],

       [[141.4,  94. ,  49.6]],

       [[ 61.8, -26.9, -53. ]]])

In [46]:
A=np.array([[1,-1,2,4,0],[8,2,0,5,3],[0,1,2,1,2]])
print(A)

B=np.array([[1,0,1,0],[0,0,2,-1],[1,0,1,1],[0,1,1,1],[1,1,0,-1]])
print(B)

[[ 1 -1  2  4  0]
 [ 8  2  0  5  3]
 [ 0  1  2  1  2]]
[[ 1  0  1  0]
 [ 0  0  2 -1]
 [ 1  0  1  1]
 [ 0  1  1  1]
 [ 1  1  0 -1]]


In [47]:
C = np.dot(A,B)
C

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])

In [48]:
C[0][1]

4

In [49]:
C[2][3]

0

In [50]:
A=np.array([[1,2,1],[4,4,4]])

B=np.array([[1,0,6,1],[0,1,0,1],[6,0,1,1]])

In [51]:
C = np.dot(A,B)

In [52]:
C.shape

(2, 4)

In [58]:
A=np.array([1,3])

B=np.array([-3,1])

C = np.tensordot(A, B, axes=0)

C

array([[-3,  1],
       [-9,  3]])

In [79]:
A=np.array([1,1])

B=np.array([2,-1])

C=np.array([1,2])

In [80]:
A * A.T

array([1, 1])

In [81]:
B * B.T

array([4, 1])

In [82]:
C * C.T

array([1, 4])

In [83]:
A * B * C * (A * B * C).T

array([4, 4])

In [102]:
# Найдите матрицу Грама G системы векторов

Z=np.array([[1,1],[2,-1],[1,2]])
Z

array([[ 1,  1],
       [ 2, -1],
       [ 1,  2]])

In [86]:
Z.T

array([[ 1,  2,  1],
       [ 1, -1,  2]])

In [101]:
np.dot(Z, Z.T)

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

In [103]:
Z@Z.T

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])