In [3]:
import numpy as np
import pandas as pd

In [4]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

In [11]:
np.random.randint(0, 4, (3, 3))

array([[2, 1, 1],
       [1, 2, 3],
       [0, 0, 1]])

In [12]:
np.random.randint(0, 5, (3, 3))

array([[3, 2, 2],
       [0, 2, 0],
       [0, 3, 4]])

In [13]:
np.random.randint(0, 6, (3, 3))

array([[0, 1, 4],
       [5, 0, 2],
       [2, 1, 1]])

In [14]:
np.random.randint(0, 5, 3)

array([2, 4, 1])

In [15]:
np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.ones((4, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.full((4, 4), 1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.array(range(9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [24]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [33]:
my_array = np.array([x for x in range(10)])

In [34]:
my_array[5]

5

In [35]:
my_array[-1]

9

In [36]:
my_array[3:6]

array([3, 4, 5])

In [37]:
my_array[1:8:3]

array([1, 4, 7])

In [38]:
my_array[1:8:3]

array([1, 4, 7])

In [39]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])

In [43]:
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [40]:
my_array[1][2]

12

In [41]:
my_array[1,2]

12

In [42]:
my_array[1]

array([10, 11, 12, 13])

In [44]:
my_array[:, 2]

array([ 3, 12, 47])

In [46]:
my_array[1:, 1:3]

array([[11, 12],
       [46, 47]])

In [93]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [94]:
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [103]:
"""
Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:
"""

result = big_secret[:5, -1:].sum()
round(result, 2)

3154.33

In [131]:
"""
Выделите из каждой строки массива big_secret первые 5 элементов.

Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

"""

big_secret_1 = big_secret[:5, :5]

# сумма элементов главной диагонали
sumMain = 0

for i in range(5):
    # У элементов главной диагонали совпадают оба индекса.
    # Из матрицы извлекается элемент и добавляется к сумме.
    sumMain += big_secret_1[i][i]
    
# вывод сумм
print(round(sumMain, 2))

121.37


In [134]:
"""
Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы?
Введите полученный результат без изменений и округлений.

"""

big_secret_2 = big_secret[:5, -5:]

# сумма элементов главной диагонали
sumMain2 = 1

for i in range(5):
    # У элементов главной диагонали совпадают оба индекса.
    # Из матрицы извлекается элемент и добавляется к сумме.
    sumMain2 *= big_secret_2[i][i]
    
# вывод сумм
print(round(sumMain2, 2))

341505315559.23


In [135]:
my_array = np.random.randint(1, 100, (4, 6))

my_array

array([[92, 63, 94, 16, 83, 68],
       [14, 97, 42, 95, 84, 76],
       [74, 54, 29, 86, 34, 90],
       [ 3, 69, 10, 96, 17, 55]])

In [136]:
my_slice = my_array[1:3, 2:4]

my_slice

array([[42, 95],
       [29, 86]])

In [137]:
my_slice[:] = 0

In [138]:
my_array

array([[92, 63, 94, 16, 83, 68],
       [14, 97,  0,  0, 84, 76],
       [74, 54,  0,  0, 34, 90],
       [ 3, 69, 10, 96, 17, 55]])

In [160]:
for x in range(5):
    for y in range(51):
        if x%2 == 0 and y%2 == 0:
            big_secret[x][y] = -1
        elif x%2 != 0 and y%2 != 0:
            big_secret[x][y] = 1

big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

In [161]:
"""
Выделите из каждой строки обновлённого массива big_secret первые 5 элементов.
Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.
"""

big_secret_3 = big_secret[:5, :5]

display(big_secret_3)

# сумма элементов главной диагонали
sumMain = 0

for i in range(5):
    # У элементов главной диагонали совпадают оба индекса.
    # Из матрицы извлекается элемент и добавляется к сумме.
    sumMain += big_secret_3[i][i]
    
# вывод сумм
print(sumMain)

np.diagonal(big_secret_3).sum()

array([[-1.        , 10.        , -1.        , 56.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        ,  1.        , -1.        ,  9.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        , 10.        , -1.        , 56.        , -1.        ]])

-1.0


-1.0

In [162]:
"""
Выделите из каждой строки обновлённого массива big_secret последние 5 элементов.
Чему равно произведение элементов главной диагонали получившейся матрицы?
Введите полученный результат без изменений и округлений.

"""

big_secret_4 = big_secret[:5, -5:]

display(big_secret)

# сумма элементов главной диагонали
sumMain4 = 1

for i in range(5):
    # У элементов главной диагонали совпадают оба индекса.
    # Из матрицы извлекается элемент и добавляется к сумме.
    sumMain4 *= big_secret_4[i][i]
    
# вывод сумм
print(sumMain4)

np.diagonal(big_secret_4).prod()

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

-1.0


-1.0

In [163]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [168]:
"""
Рассмотрим список часто используемых универсальных функций NumPy.

При вызове каждой из этих функций необходимо указывать название библиотеки NumPy: np.isnan(имя_массива):

Функция Описание
abs Абсолютное значение целых, вещественных или комплексных элементов массива
sqrt Квадратный корень каждого элемента массива
exp Экспонента (ex) каждого элемента массива
log, log10, log2, log1p Натуральный (по основанию е), десятичный, двоичный логарифм и функция log(1+x) соответственно
modf Дробные и целые части массива в виде отдельных массивов
isnan Массив логических (булевых) значений, показывающий, какие из элементов исходного массива  являются NaN (не числами)
cos, sin, tan Обычные тригонометрические функции
arccos, arcsin, arctan Обратные тригонометрические функции


"""

print('Done')

Done


In [173]:
"""

Для превращения массива одной размерности в массив другой — обычно для преобразования одномерного массива в многомерный — используется метод reshape.

Изменить размерность массива можно только в том случае, если число элементов в исходном и в целевом массиве совпадает:
"""

my_array = np.random.randint(0, 10, 20)
my_array


my_array.reshape((4,5))

array([[3, 0, 9, 9, 3],
       [7, 4, 1, 6, 1],
       [0, 6, 2, 5, 8],
       [9, 6, 2, 7, 2]])

In [174]:
"""
В некоторых задачах машинного обучения для подготовки данных к обработке нужно изменить исходную форму массива,
например, преобразовать многомерный массив в одномерный, поменять местами строки и столбцы.

Замена местами строк и столбцов двумерного массива называется транспонированием.

Для выполнения этой операции в NumPy используется метод T:

"""

my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [175]:
"""
Для преобразования многомерного массива в одномерный используется метод flatten:

"""

my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [177]:
"""
Сравнения и маски
Научимся сравнивать элементы массива с числом и извлекать из него только те элементы, которые больше или меньше заданного числа. Для этого создадим массив размера 3х4, произвольно заполненный числами от 0 до 10.
При создании массива используется генератор случайных чисел, так что у вас могут получиться другие значения:

"""

my_array = np.random.randint(0, 10, (3,4))

my_array<5

array([[False, False, False, False],
       [False, False, False,  True],
       [ True, False, False,  True]])

In [178]:
"""
Мы получили новый массив, заполненный значениями True/False в зависимости от того, меньше или больше пяти элемент,
находящийся на соответствующей позиции в исходном массиве. Для того, чтобы получить элементы массива my_array,
которые меньше пяти, воспользуемся кодом ниже.
Отобранные элементы представляют собой одномерный массив.

"""

my_array[my_array<5]

array([4, 0, 3])

In [179]:
"""
Маска нужна для выбора только определенных строк или столбцов из всего массива и скрытия остальных.
Маска в Python задаётся при помощи булевых 0 и 1, где 0 скрывает столбец или строку, а 1 оставляет ее на виду.
Выведем первый и третрий столбец массива:

"""

mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[7, 6],
       [8, 9],
       [0, 7]])

In [180]:
"""
Сортировка двумерных массивов
В двумерных массивах можно выполнять сортировку элементов строк и столбцов:

Сортировка выполняется с помощью функции sort, в качестве параметров функция получает сам массив,
а также номер оси (0 (для столбцов) или 1 (для строк)) , элементы которой необходимо отсортировать. 

Как можно отсортировать элементы строк и столбцов?

Отсортируем элементы строк:

"""

my_array = np.random.randint(0, 10, (4, 6))

np.sort(my_array, axis=1)

np.sort(my_array, axis=0)

array([[0, 3, 2, 2, 4, 2],
       [1, 4, 2, 3, 5, 2],
       [4, 5, 5, 6, 7, 3],
       [9, 6, 6, 8, 8, 7]])

In [184]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

In [187]:
great_secret[0]


print(round(np.cos(great_secret[0]).sum(), 2))

0.16


In [189]:
"""
Чему равна сумма элементов массива great_secret, значение которых больше 50?

"""
great_secret[great_secret>50].sum()

5470.0

In [197]:
"""
Переведите массив great_secret в одномерную форму.
Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

"""

a = great_secret.flatten()
a[150]

7.0710678118654755

In [202]:
"""
Отсортируйте значения столбцов массива great_secret по возрастанию.
Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

"""
great_secret

a = np.sort(great_secret, axis=0)

# print(a)

print(round(a[-1].sum(), 2))

115.12


In [207]:
import numpy as np
students = np.array([[1,135,34,4],[2,160,43,5],[3,163,40,4.3],[4,147,44,5],[5,138,41,4.7],[6,149,54,3.9],[7,136,39,4.2],[8,154,48,5.9],[9,137,35,3.7],[10,165,60,4.6]], dtype=float)
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   5.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [208]:
mean = np.mean(students[:,-1])
mean

4.53

In [209]:
median = np.median(students[:,-1])
median

4.449999999999999

In [210]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

In [211]:
median = np.median(students[:,-2])
median

42.0

In [220]:
median = np.median(students[:,-2])
mean = np.mean(students[:,-2])
(round((mean - median), 2))

1.8

In [221]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [222]:
corr = np.corrcoef(students[:,1], students[:,1])
corr

array([[1., 1.],
       [1., 1.]])

In [223]:
corr = np.corrcoef(students[:,1], students[:,3])
corr

array([[1.        , 0.41682049],
       [0.41682049, 1.        ]])

In [225]:
corr = np.corrcoef(students[:,0], students[:,1])
corr

array([[1.        , 0.06596634],
       [0.06596634, 1.        ]])

In [226]:
corr = np.corrcoef(students[:,0], students[:,2])
corr

array([[1.        , 0.48397415],
       [0.48397415, 1.        ]])

In [227]:
corr = np.corrcoef(students[:,0], students[:,3])
corr

array([[1.        , 0.03073717],
       [0.03073717, 1.        ]])

In [229]:
corr = np.corrcoef(students[:,1], students[:,3])
corr

array([[1.        , 0.41682049],
       [0.41682049, 1.        ]])

In [230]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [231]:
corr = np.corrcoef(students[:,1], students[:,0])
corr

array([[1.        , 0.06596634],
       [0.06596634, 1.        ]])

In [232]:
corr = np.corrcoef(students[:,2], students[:,3])
corr

array([[1.        , 0.30289181],
       [0.30289181, 1.        ]])

In [234]:
corr = np.corrcoef(students[:,3], students[:,2])
corr

array([[1.        , 0.30289181],
       [0.30289181, 1.        ]])

In [235]:
std = np.std(students[:,1])
std

11.083320801997928

In [243]:
std = np.std(students[:,3])
std

0.6229767250869009

In [247]:
"""
Посчитайте, чему равна дисперсия значений веса школьников.
"""

std = np.var(students, axis=0)
std

array([  8.25  , 122.84  ,  60.36  ,   0.3881])

In [248]:
np.empty((5, 1))

array([[7.74860419e-304],
       [7.74860419e-304],
       [7.74860419e-304],
       [7.74860419e-304],
       [7.74860419e-304]])

In [249]:
np.ones((5,10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [250]:
np.full((10, 5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [251]:
np.array([x/x for x in range(1,10)]*5)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [252]:
np.random.randint(1, 10, (10, 10))

array([[2, 9, 7, 7, 9, 2, 3, 5, 6, 2],
       [4, 8, 5, 1, 4, 5, 6, 6, 5, 7],
       [1, 7, 5, 8, 8, 9, 9, 7, 4, 7],
       [3, 5, 3, 8, 7, 8, 5, 9, 5, 9],
       [7, 7, 6, 7, 2, 2, 8, 4, 5, 2],
       [6, 1, 1, 7, 7, 4, 4, 3, 5, 2],
       [7, 8, 4, 7, 8, 8, 7, 7, 4, 1],
       [9, 7, 3, 8, 5, 4, 3, 9, 2, 6],
       [9, 4, 2, 8, 2, 7, 4, 9, 3, 8],
       [7, 9, 5, 4, 5, 5, 1, 7, 6, 8]])

In [254]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [257]:
my_array[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [260]:
my_sin = np.sin(my_array)
round((my_sin.sum()), 3)

-0.058

In [267]:
"""
Замените элементы в центральном фрагменте 3 х 3 массива my_sin на единицы.
Чему равна сумма элементов изменённого массива? Ответ округлите до трёх знаков после запятой.

"""

display(my_sin)

my_sin[1:4,1:4] = 1

# my_slice[:] = 0

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [270]:
round((my_sin.sum()), 3)

7.572

In [285]:
"""
Преобразуйте первые 4 столбца массива my_sin в массив из 10 строк и 2 столбцов.
Чему равна сумма элементов первого столбца получившегося массива? Ответ округлите до трёх заков после запятой.

"""
new_my_sin = my_sin[:, 0:4]

new_my_sin2 = new_my_sin.reshape((10,2))
round((new_my_sin2[:, 0].sum()), 3)

2.406

In [286]:
bigdata = [x**2 for x in range(100, 1001) if x%2 != 0]
bigdata

[10201,
 10609,
 11025,
 11449,
 11881,
 12321,
 12769,
 13225,
 13689,
 14161,
 14641,
 15129,
 15625,
 16129,
 16641,
 17161,
 17689,
 18225,
 18769,
 19321,
 19881,
 20449,
 21025,
 21609,
 22201,
 22801,
 23409,
 24025,
 24649,
 25281,
 25921,
 26569,
 27225,
 27889,
 28561,
 29241,
 29929,
 30625,
 31329,
 32041,
 32761,
 33489,
 34225,
 34969,
 35721,
 36481,
 37249,
 38025,
 38809,
 39601,
 40401,
 41209,
 42025,
 42849,
 43681,
 44521,
 45369,
 46225,
 47089,
 47961,
 48841,
 49729,
 50625,
 51529,
 52441,
 53361,
 54289,
 55225,
 56169,
 57121,
 58081,
 59049,
 60025,
 61009,
 62001,
 63001,
 64009,
 65025,
 66049,
 67081,
 68121,
 69169,
 70225,
 71289,
 72361,
 73441,
 74529,
 75625,
 76729,
 77841,
 78961,
 80089,
 81225,
 82369,
 83521,
 84681,
 85849,
 87025,
 88209,
 89401,
 90601,
 91809,
 93025,
 94249,
 95481,
 96721,
 97969,
 99225,
 100489,
 101761,
 103041,
 104329,
 105625,
 106929,
 108241,
 109561,
 110889,
 112225,
 113569,
 114921,
 116281,
 117649,
 119025,
 

In [287]:
median_bigdata = np.median(bigdata)
median_bigdata

302501.0

In [289]:
"""
Чему равно стандартное отклонение для массива bigdata? Ответ округлите до целых:
"""

std_bigdata = np.std(bigdata)
round(std_bigdata)

292095.0

In [319]:
"""
Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами?
Введите полученный ответ без изменений и округлений.

"""
# first_line = [x**2 for x in range(100, 1001) if x%2 != 0]

# bigdata = np.array([first_line])

# new_bigdata = bigdata.reshape((2,225))

# corr = np.corrcoef(new_bigdata[0], new_bigdata[1])
# corr

first_line = [x**2 for x in range(100, 1001) if x%2 != 0]
bigdata = np.array(first_line)
odd = bigdata[1::2]
even = bigdata[0::2]
corr = np.corrcoef(even, odd)
corr

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])